# Generated by Django 5.1.3 on 2025-02-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_delete_dash_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('member', 'Member'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
