# Generated by Django 5.1.3 on 2025-02-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('member', 'Member'), ('admin', 'Admin')], default='member', max_length=10),
        ),
    ]
