# Generated by Django 5.1.6 on 2025-03-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'อิเล็กทรอนิกส์'), ('clothing', 'เสื้อผ้า'), ('accessories', 'อุปกรณ์เสริม'), ('home_appliances', 'เครื่องใช้ไฟฟ้าภายในบ้าน'), ('books', 'หนังสือ'), ('others', 'อื่นๆ')], default='others', max_length=100),
        ),
    ]
