# Generated by Django 5.1.6 on 2025-03-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storepayment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
