# Generated by Django 5.1.6 on 2025-03-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_storepayment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storepayment',
            name='payment_method',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
